steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA']

  # Run the database seeder
  - name: 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA'
    entrypoint: 'python3'
    args: ['./scripts/seed_db.py']
    env:
      - 'MONGO_URI=${_MONGO_URI}'
      - 'MONGO_DATABASE=${_MONGO_DATABASE}'
      - 'SECRET_KEY=${_SECRET_KEY}'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'playfriends-backend' # your service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # e.g., us-central1
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGO_URI=${_MONGO_URI},MONGO_DATABASE=${_MONGO_DATABASE},SECRET_KEY=${_SECRET_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA'

substitutions:
  _MONGO_URI: 'your-mongodb-uri'
  _MONGO_DATABASE: 'your-db-name'
  _SECRET_KEY: 'your-secret-key'

options:
  logging: CLOUD_LOGGING_ONLY
