steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'playfriends-backend' # your service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # e.g., us-central1
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGO_URI=${_MONGO_URI}' # Pass environment variable from build trigger

images:
  - 'gcr.io/$PROJECT_ID/playfriends-backend:$COMMIT_SHA'

substitutions:
  _MONGO_URI: 'your-mongodb-atlas-uri-here' # Default value, will be overridden by trigger

options:
  logging: CLOUD_LOGGING_ONLY
