from app.models.activity import ActivityModel, FoodAttributes, PlayAttributes, GeoJson
from app.core.enums import (
    ActivityType,
    FoodIngredient,
    FoodTaste,
    FoodCookingMethod,
    FoodCuisineType,
)

def get_dummy_activities(category_ids):
    """
    대전 지역의 활동 더미 데이터를 반환하는 함수.
    """
    activities = [
        # === 놀거리 (Activity) ===
        # --- 공원 & 자연 ---
        ActivityModel(name="한밭수목원", type=ActivityType.ACTIVITY, category_id=category_ids.get("산책"), location=GeoJson(coordinates=[127.3859, 36.3699]), play_attributes=PlayAttributes(crowd_level=-0.5, activeness_level=-0.7, location_preference=-1.0, vibe_level=-0.8)),
        ActivityModel(name="장태산자연휴양림", type=ActivityType.ACTIVITY, category_id=category_ids.get("야외활동"), location=GeoJson(coordinates=[127.3332, 36.2204]), play_attributes=PlayAttributes(crowd_level=-0.6, activeness_level=0.2, location_preference=-1.0, vibe_level=-0.9)),
        ActivityModel(name="뿌리공원", type=ActivityType.ACTIVITY, category_id=category_ids.get("관광"), location=GeoJson(coordinates=[127.4031, 36.2884]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=-0.2, location_preference=-0.8, vibe_level=-0.4)),
        ActivityModel(name="상소동 산림욕장", type=ActivityType.ACTIVITY, category_id=category_ids.get("야외활동"), location=GeoJson(coordinates=[127.4942, 36.2446]), play_attributes=PlayAttributes(crowd_level=-0.7, activeness_level=0.3, location_preference=-1.0, vibe_level=-0.9)),
        ActivityModel(name="대청호 오백리길", type=ActivityType.ACTIVITY, category_id=category_ids.get("산책"), location=GeoJson(coordinates=[127.484, 36.474]), play_attributes=PlayAttributes(crowd_level=-0.8, activeness_level=0.5, location_preference=-1.0, vibe_level=-0.7)),
        ActivityModel(name="계족산 황톳길", type=ActivityType.ACTIVITY, category_id=category_ids.get("등산"), location=GeoJson(coordinates=[127.462, 36.391]), play_attributes=PlayAttributes(crowd_level=-0.4, activeness_level=0.6, location_preference=-1.0, vibe_level=-0.6)),
        ActivityModel(name="유림공원", type=ActivityType.ACTIVITY, category_id=category_ids.get("산책"), location=GeoJson(coordinates=[127.3801, 36.3682]), play_attributes=PlayAttributes(crowd_level=-0.2, activeness_level=-0.6, location_preference=-0.9, vibe_level=-0.5)),
        ActivityModel(name="보문산", type=ActivityType.ACTIVITY, category_id=category_ids.get("등산"), location=GeoJson(coordinates=[127.418, 36.304]), play_attributes=PlayAttributes(crowd_level=-0.3, activeness_level=0.7, location_preference=-1.0, vibe_level=-0.5)),
        ActivityModel(name="우암사적공원", type=ActivityType.ACTIVITY, category_id=category_ids.get("관광"), location=GeoJson(coordinates=[127.447, 36.341]), play_attributes=PlayAttributes(crowd_level=-0.7, activeness_level=-0.8, location_preference=-0.7, vibe_level=-0.9)),
        ActivityModel(name="대동하늘공원", type=ActivityType.ACTIVITY, category_id=category_ids.get("관광"), location=GeoJson(coordinates=[127.442, 36.336]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=-0.5, trend_level=0.4, location_preference=-0.8, vibe_level=0.3)),

        # --- 박물관 & 미술관 ---
        ActivityModel(name="국립중앙과학관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.385, 36.377]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.3, location_preference=1.0, vibe_level=-0.2)),
        ActivityModel(name="대전시립미술관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.386, 36.372]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=-0.9, trend_level=0.2, location_preference=1.0, vibe_level=-0.7)),
        ActivityModel(name="이응노미술관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.384, 36.372]), play_attributes=PlayAttributes(crowd_level=0.0, activeness_level=-0.9, trend_level=0.5, location_preference=1.0, vibe_level=-0.6)),
        ActivityModel(name="화폐박물관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.383, 36.381]), play_attributes=PlayAttributes(crowd_level=-0.2, activeness_level=-0.8, location_preference=1.0, vibe_level=-0.5)),
        ActivityModel(name="지질박물관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.380, 36.388]), play_attributes=PlayAttributes(crowd_level=-0.1, activeness_level=-0.7, location_preference=1.0, vibe_level=-0.4)),
        ActivityModel(name="대전근현대사전시관", type=ActivityType.ACTIVITY, category_id=category_ids.get("미술관, 박물관"), location=GeoJson(coordinates=[127.425, 36.328]), play_attributes=PlayAttributes(crowd_level=-0.3, activeness_level=-0.8, location_preference=1.0, vibe_level=-0.6)),

        # --- 테마파크 & 엔터테인먼트 ---
        ActivityModel(name="대전 오월드", type=ActivityType.ACTIVITY, category_id=category_ids.get("놀이공원"), location=GeoJson(coordinates=[127.3969, 36.2924]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=0.8, trend_level=0.5, vibe_level=0.9)),
        ActivityModel(name="대전 아쿠아리움", type=ActivityType.ACTIVITY, category_id=category_ids.get("동물원"), location=GeoJson(coordinates=[127.418, 36.308]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.1, location_preference=1.0, vibe_level=0.5)),
        ActivityModel(name="엑스포 과학공원 한빛탑", type=ActivityType.ACTIVITY, category_id=category_ids.get("관광"), location=GeoJson(coordinates=[127.3863, 36.3763]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=-0.4, trend_level=-0.2, location_preference=-0.5)),
        ActivityModel(name="CGV 대전터미널", type=ActivityType.ACTIVITY, category_id=category_ids.get("영화관"), location=GeoJson(coordinates=[127.4323, 36.3523]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.9, location_preference=1.0, vibe_level=-0.5)),
        ActivityModel(name="메가박스 대전신세계", type=ActivityType.ACTIVITY, category_id=category_ids.get("영화관"), location=GeoJson(coordinates=[127.385, 36.375]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.9, trend_level=0.7, location_preference=1.0, vibe_level=-0.4)),
        ActivityModel(name="타임월드 보드게임카페", type=ActivityType.ACTIVITY, category_id=category_ids.get("보드게임카페"), location=GeoJson(coordinates=[127.3828, 36.3522]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=0.1, planning_level=-0.5, location_preference=1.0, vibe_level=0.4)),
        ActivityModel(name="궁동 로데오거리", type=ActivityType.ACTIVITY, category_id=category_ids.get("쇼핑"), location=GeoJson(coordinates=[127.346, 36.362]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=0.3, trend_level=0.8, location_preference=-0.2, vibe_level=0.7)),
        ActivityModel(name="으능정이 문화의 거리", type=ActivityType.ACTIVITY, category_id=category_ids.get("쇼핑"), location=GeoJson(coordinates=[127.428, 36.329]), play_attributes=PlayAttributes(crowd_level=0.9, activeness_level=0.2, trend_level=0.6, location_preference=-0.4, vibe_level=0.8)),
        ActivityModel(name="대전 스카이로드", type=ActivityType.ACTIVITY, category_id=category_ids.get("관광"), location=GeoJson(coordinates=[127.428, 36.328]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.6, trend_level=0.5, location_preference=-0.5, vibe_level=0.6)),
        ActivityModel(name="소제동 카페거리", type=ActivityType.ACTIVITY, category_id=category_ids.get("이색 데이트"), location=GeoJson(coordinates=[127.433, 36.333]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.5, trend_level=0.9, location_preference=-0.3, vibe_level=0.5)),
        ActivityModel(name="대흥동 문화예술의 거리", type=ActivityType.ACTIVITY, category_id=category_ids.get("이색 데이트"), location=GeoJson(coordinates=[127.426, 36.325]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.6, trend_level=0.4, location_preference=-0.4, vibe_level=0.2)),
        ActivityModel(name="유성온천 족욕체험장", type=ActivityType.ACTIVITY, category_id=category_ids.get("이색 데이트"), location=GeoJson(coordinates=[127.352, 36.354]), play_attributes=PlayAttributes(crowd_level=-0.1, activeness_level=-0.8, location_preference=-0.7, vibe_level=-0.9)),
        ActivityModel(name="대전시민천문대", type=ActivityType.ACTIVITY, category_id=category_ids.get("문화생활"), location=GeoJson(coordinates=[127.380, 36.391]), play_attributes=PlayAttributes(crowd_level=-0.4, activeness_level=-0.9, location_preference=1.0, vibe_level=-0.7)),
        ActivityModel(name="대전월드컵경기장", type=ActivityType.ACTIVITY, category_id=category_ids.get("경기관람"), location=GeoJson(coordinates=[127.341, 36.369]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=-0.2, vibe_level=0.9)),
        ActivityModel(name="한화생명이글스파크", type=ActivityType.ACTIVITY, category_id=category_ids.get("경기관람"), location=GeoJson(coordinates=[127.419, 36.318]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=-0.2, vibe_level=0.9)),
    ]
    activities.extend([
        # === 음식 (Food) ===
        # --- 한식 ---
        ActivityModel(name="성심당 본점", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.4288, 36.3279]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.EGG, FoodIngredient.MILK], tastes=[FoodTaste.SWEET], cooking_methods=[])),
        ActivityModel(name="오씨칼국수", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.4196, 36.3345]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.FISH], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="태평소국밥", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.3957, 36.3365]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="광천식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.4291, 36.3268]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.FISH], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="진로집", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.428, 36.325]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.VEGETABLE], tastes=[FoodTaste.SPICY, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="대선칼국수", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.383, 36.352]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="한영식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.412, 36.312]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SPICY, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="사리원면옥", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.425, 36.329]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[], cooking_methods=[FoodCookingMethod.RAW])),
        ActivityModel(name="전미원", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.340, 36.318]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[], cooking_methods=[FoodCookingMethod.GRILL])),

        # --- 양식, 중식, 일식, 기타 ---
        ActivityModel(name="컬리나리아", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.350, 36.360]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.FISH], tastes=[], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="동북아", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.434, 36.332]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.CHINESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="치앙마이방콕", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.433, 36.331]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.SOUTEAST_ASIAN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.FISH], tastes=[FoodTaste.SOUR, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="룸비니", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.345, 36.363]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.SOUTEAST_ASIAN], ingredients=[FoodIngredient.MEAT, FoodIngredient.VEGETABLE], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.STEAMED])),
        ActivityModel(name="타코앤칩스", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.381, 36.353]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.MEAT, FoodIngredient.VEGETABLE], tastes=[FoodTaste.SALTY, FoodTaste.SOUR], cooking_methods=[])),
        ActivityModel(name="라쿠시나에비노", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.378, 36.355]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MILK, FoodIngredient.FLOUR], tastes=[], cooking_methods=[FoodCookingMethod.STIR_FRIED])),

        # --- 카페 & 디저트 ---
        ActivityModel(name="풍류소제", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.432, 36.332]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.7, trend_level=0.8, vibe_level=0.5)),
        ActivityModel(name="두두당", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.435, 36.331]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=-0.6, trend_level=0.7, vibe_level=0.4)),
        ActivityModel(name="공간태리", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.341, 36.316]), play_attributes=PlayAttributes(crowd_level=-0.3, activeness_level=-0.8, trend_level=0.6, vibe_level=-0.2)),
        ActivityModel(name="서로히", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.383, 36.351]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=-0.7, trend_level=0.7, vibe_level=0.3)),
        ActivityModel(name="알로하녹", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.362, 36.358]), play_attributes=PlayAttributes(crowd_level=-0.1, activeness_level=-0.6, trend_level=0.5, vibe_level=0.2)),
        ActivityModel(name="롤라", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.490, 36.470]), play_attributes=PlayAttributes(crowd_level=-0.5, activeness_level=-0.5, trend_level=0.4, vibe_level=0.1)),
        ActivityModel(name="점선면", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.430, 36.326]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.4, trend_level=0.6, vibe_level=0.4)),
        ActivityModel(name="프랭크커핀바", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.375, 36.354]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.6, trend_level=0.9, vibe_level=0.6)),
    ])
    
    # =================================================================================================
    # ======================================= 추가된 데이터 (100개) =======================================
    # =================================================================================================
    
    additional_activities = [
        # --- 문화생활 (10개) ---
        ActivityModel(name="대전아트시네마", type=ActivityType.ACTIVITY, category_id=category_ids.get("영화관"), location=GeoJson(coordinates=[127.425, 36.328]), play_attributes=PlayAttributes(crowd_level=-0.2, activeness_level=-0.9, trend_level=-0.5, vibe_level=-0.6)),
        ActivityModel(name="롯데시네마 대전센트럴", type=ActivityType.ACTIVITY, category_id=category_ids.get("영화관"), location=GeoJson(coordinates=[127.410, 36.330]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.9, vibe_level=-0.5)),
        ActivityModel(name="대전예술의전당", type=ActivityType.ACTIVITY, category_id=category_ids.get("뮤지컬"), location=GeoJson(coordinates=[127.387, 36.370]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=-0.9, trend_level=0.3, vibe_level=-0.7)),
        ActivityModel(name="가톨릭문화회관 아트홀", type=ActivityType.ACTIVITY, category_id=category_ids.get("연극"), location=GeoJson(coordinates=[127.426, 36.326]), play_attributes=PlayAttributes(crowd_level=-0.3, activeness_level=-0.8, trend_level=-0.2, vibe_level=-0.5)),
        ActivityModel(name="충남대학교 정심화홀", type=ActivityType.ACTIVITY, category_id=category_ids.get("콘서트"), location=GeoJson(coordinates=[127.346, 36.369]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.4, trend_level=0.4, vibe_level=0.3)),
        ActivityModel(name="교보문고 대전점", type=ActivityType.ACTIVITY, category_id=category_ids.get("서점"), location=GeoJson(coordinates=[127.383, 36.353]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.8, vibe_level=-0.7)),
        ActivityModel(name="영풍문고 대전터미널점", type=ActivityType.ACTIVITY, category_id=category_ids.get("서점"), location=GeoJson(coordinates=[127.433, 36.352]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.8, vibe_level=-0.6)),
        ActivityModel(name="대전시립연정국악원", type=ActivityType.ACTIVITY, category_id=category_ids.get("콘서트"), location=GeoJson(coordinates=[127.388, 36.371]), play_attributes=PlayAttributes(crowd_level=-0.1, activeness_level=-0.7, trend_level=-0.3, vibe_level=-0.8)),
        ActivityModel(name="아신극장", type=ActivityType.ACTIVITY, category_id=category_ids.get("연극"), location=GeoJson(coordinates=[127.427, 36.324]), play_attributes=PlayAttributes(crowd_level=-0.4, activeness_level=-0.8, trend_level=-0.4, vibe_level=-0.4)),
        ActivityModel(name="대전독립영화관", type=ActivityType.ACTIVITY, category_id=category_ids.get("영화관"), location=GeoJson(coordinates=[127.429, 36.328]), play_attributes=PlayAttributes(crowd_level=-0.7, activeness_level=-0.9, trend_level=0.1, vibe_level=-0.6)),

        # --- 쇼핑 (5개) ---
        ActivityModel(name="갤러리아타임월드", type=ActivityType.ACTIVITY, category_id=category_ids.get("백화점"), location=GeoJson(coordinates=[127.382, 36.352]), play_attributes=PlayAttributes(crowd_level=0.7, trend_level=0.8, location_preference=1.0)),
        ActivityModel(name="대전신세계 Art & Science", type=ActivityType.ACTIVITY, category_id=category_ids.get("백화점"), location=GeoJson(coordinates=[127.385, 36.375]), play_attributes=PlayAttributes(crowd_level=0.8, trend_level=0.9, location_preference=1.0)),
        ActivityModel(name="현대프리미엄아울렛 대전점", type=ActivityType.ACTIVITY, category_id=category_ids.get("아울렛"), location=GeoJson(coordinates=[127.398, 36.408]), play_attributes=PlayAttributes(crowd_level=0.6, trend_level=0.5, location_preference=-0.5)),
        ActivityModel(name="은행동 지하상가", type=ActivityType.ACTIVITY, category_id=category_ids.get("쇼핑"), location=GeoJson(coordinates=[127.428, 36.329]), play_attributes=PlayAttributes(crowd_level=0.9, trend_level=0.2, location_preference=1.0)),
        ActivityModel(name="대전 중앙시장", type=ActivityType.ACTIVITY, category_id=category_ids.get("쇼핑"), location=GeoJson(coordinates=[127.432, 36.331]), play_attributes=PlayAttributes(crowd_level=0.9, trend_level=-0.5, location_preference=-0.7)),

        # --- 엔터테인먼트 (15개) ---
        ActivityModel(name="짱PC방 둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("피시방"), location=GeoJson(coordinates=[127.381, 36.351]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=0.2, vibe_level=0.4)),
        ActivityModel(name="라이또PC방 은행점", type=ActivityType.ACTIVITY, category_id=category_ids.get("피시방"), location=GeoJson(coordinates=[127.427, 36.329]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=0.2, vibe_level=0.3)),
        ActivityModel(name="락휴 코인노래연습장 둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("노래방"), location=GeoJson(coordinates=[127.380, 36.353]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=0.7, vibe_level=0.8)),
        ActivityModel(name="세븐스타 코인노래방 충남대점", type=ActivityType.ACTIVITY, category_id=category_ids.get("노래방"), location=GeoJson(coordinates=[127.348, 36.363]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=0.7, vibe_level=0.7)),
        ActivityModel(name="레드버튼 보드게임카페 둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("보드게임카페"), location=GeoJson(coordinates=[127.381, 36.354]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=0.1, planning_level=-0.4, vibe_level=0.5)),
        ActivityModel(name="홈즈앤루팡 보드게임카페 대전은행점", type=ActivityType.ACTIVITY, category_id=category_ids.get("보드게임카페"), location=GeoJson(coordinates=[127.428, 36.327]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=0.1, planning_level=-0.4, vibe_level=0.6)),
        ActivityModel(name="이스케이프탑 대전점 (방탈출)", type=ActivityType.ACTIVITY, category_id=category_ids.get("방탈출 카페"), location=GeoJson(coordinates=[127.383, 36.355]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=0.5, planning_level=0.8, vibe_level=0.7)),
        ActivityModel(name="셜록홈즈 방탈출카페 대전둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("방탈출 카페"), location=GeoJson(coordinates=[127.379, 36.352]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=0.5, planning_level=0.8, vibe_level=0.6)),
        ActivityModel(name="코리아당구클럽", type=ActivityType.ACTIVITY, category_id=category_ids.get("당구장"), location=GeoJson(coordinates=[127.347, 36.362]), play_attributes=PlayAttributes(crowd_level=0.1, activeness_level=0.4, vibe_level=0.2)),
        ActivityModel(name="둔산 프로볼링장", type=ActivityType.ACTIVITY, category_id=category_ids.get("볼링장"), location=GeoJson(coordinates=[127.375, 36.351]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=0.8, vibe_level=0.6)),
        ActivityModel(name="월드컵볼링경기장", type=ActivityType.ACTIVITY, category_id=category_ids.get("볼링장"), location=GeoJson(coordinates=[127.340, 36.370]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=0.8, vibe_level=0.5)),
        ActivityModel(name="벌툰 만화카페 은행점", type=ActivityType.ACTIVITY, category_id=category_ids.get("만화방"), location=GeoJson(coordinates=[127.427, 36.328]), play_attributes=PlayAttributes(crowd_level=-0.2, activeness_level=-0.8, location_preference=1.0, vibe_level=-0.7)),
        ActivityModel(name="놀숲 만화카페 대전시청점", type=ActivityType.ACTIVITY, category_id=category_ids.get("만화방"), location=GeoJson(coordinates=[127.384, 36.350]), play_attributes=PlayAttributes(crowd_level=-0.1, activeness_level=-0.8, location_preference=1.0, vibe_level=-0.6)),
        ActivityModel(name="클라이밍짐 리드", type=ActivityType.ACTIVITY, category_id=category_ids.get("엔터테인먼트"), location=GeoJson(coordinates=[127.378, 36.358]), play_attributes=PlayAttributes(activeness_level=0.9, planning_level=0.2, vibe_level=0.7)),
        ActivityModel(name="대전 챔피언 1250", type=ActivityType.ACTIVITY, category_id=category_ids.get("테마파크"), location=GeoJson(coordinates=[127.399, 36.409]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=0.9, vibe_level=0.9)),

        # --- 특별한 날 (5개) ---
        ActivityModel(name="어반라운지 파티룸", type=ActivityType.ACTIVITY, category_id=category_ids.get("파티룸"), location=GeoJson(coordinates=[127.380, 36.355]), play_attributes=PlayAttributes(crowd_level=-0.5, planning_level=0.9, vibe_level=0.8)),
        ActivityModel(name="반지마을 대전점", type=ActivityType.ACTIVITY, category_id=category_ids.get("공방 데이트"), location=GeoJson(coordinates=[127.382, 36.353]), play_attributes=PlayAttributes(activeness_level=-0.3, planning_level=0.5, trend_level=0.6, vibe_level=-0.2)),
        ActivityModel(name="향수공방 프루스트", type=ActivityType.ACTIVITY, category_id=category_ids.get("공방 데이트"), location=GeoJson(coordinates=[127.429, 36.326]), play_attributes=PlayAttributes(activeness_level=-0.4, planning_level=0.6, trend_level=0.7, vibe_level=-0.1)),
        ActivityModel(name="둔산동 흑백사진관", type=ActivityType.ACTIVITY, category_id=category_ids.get("이색 데이트"), location=GeoJson(coordinates=[127.381, 36.352]), play_attributes=PlayAttributes(activeness_level=-0.7, trend_level=0.8, vibe_level=-0.3)),
        ActivityModel(name="가죽공방 헤비츠", type=ActivityType.ACTIVITY, category_id=category_ids.get("공방 데이트"), location=GeoJson(coordinates=[127.425, 36.324]), play_attributes=PlayAttributes(activeness_level=-0.2, planning_level=0.7, trend_level=0.4, vibe_level=-0.1)),

        # --- 식당 (35개) ---
        ActivityModel(name="오문창순대국밥", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.415, 36.345]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="소나무집", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.443, 36.361]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FLOUR], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="개천식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.430, 36.330]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STEAMED])),
        ActivityModel(name="바다황제", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.375, 36.358]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FISH], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="맨오브워", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.359, 36.362]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MEAT], tastes=[], cooking_methods=[FoodCookingMethod.GRILL])),
        ActivityModel(name="잇마이타이", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.348, 36.363]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.SOUTEAST_ASIAN], ingredients=[FoodIngredient.FISH, FoodIngredient.FLOUR], tastes=[FoodTaste.SPICY, FoodTaste.SOUR], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="스바라시라멘", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.345, 36.361]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="부연부", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.426, 36.327]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.CHINESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.VEGETABLE], tastes=[], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="인터뷰맨션", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.345, 36.366]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MEAT, FoodIngredient.MILK], tastes=[], cooking_methods=[])),
        ActivityModel(name="홀리데이", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.384, 36.351]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.FLOUR], tastes=[FoodTaste.SOUR], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="피제리아616", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.349, 36.360]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MILK, FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[])),
        ActivityModel(name="월산본가", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.342, 36.319]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL])),
        ActivityModel(name="카라마데", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.377, 36.356]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.FISH], tastes=[], cooking_methods=[FoodCookingMethod.RAW])),
        ActivityModel(name="아오리라멘 대전점", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.383, 36.354]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="반갱", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.385, 36.351]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.VEGETABLE], tastes=[], cooking_methods=[])),
        ActivityModel(name="토미야", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.381, 36.350]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.FLOUR], tastes=[], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="맛찬들왕소금구이 둔산점", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.378, 36.354]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL])),
        ActivityModel(name="현대식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.431, 36.330]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="모루", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.388, 36.351]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.FLOUR, FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="희락반점", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.418, 36.340]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.CHINESE], ingredients=[FoodIngredient.FLOUR, FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="감성족발", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.349, 36.364]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STEAMED])),
        ActivityModel(name="온유네닭매운탕", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.434, 36.333]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="버기즈", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.380, 36.356]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL])),
        ActivityModel(name="코코식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.347, 36.360]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.EGG], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="미세노센세", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.346, 36.362]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SPICY, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="바질리코", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.351, 36.361]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.VEGETABLE], tastes=[], cooking_methods=[FoodCookingMethod.STIR_FRIED])),
        ActivityModel(name="태국식당", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.382, 36.351]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.SOUTEAST_ASIAN], ingredients=[FoodIngredient.FLOUR, FoodIngredient.FISH], tastes=[FoodTaste.SPICY, FoodTaste.SOUR], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="리코타코", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.379, 36.354]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.MEAT, FoodIngredient.VEGETABLE], tastes=[FoodTaste.SALTY, FoodTaste.SOUR], cooking_methods=[])),
        ActivityModel(name="인근주민", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.348, 36.365]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], ingredients=[FoodIngredient.MEAT, FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="왕가탕후루", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.429, 36.328]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.VEGETABLE], tastes=[FoodTaste.SWEET], cooking_methods=[])),
        ActivityModel(name="명랑핫도그", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.347, 36.361]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.FLOUR, FoodIngredient.MEAT], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED])),
        ActivityModel(name="이삭토스트", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.384, 36.352]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.FLOUR, FoodIngredient.EGG], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL])),
        ActivityModel(name="역전우동", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.426, 36.329]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], ingredients=[FoodIngredient.FLOUR], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP])),
        ActivityModel(name="김가네", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.381, 36.353]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.VEGETABLE], tastes=[], cooking_methods=[])),
        ActivityModel(name="한솥도시락", type=ActivityType.FOOD, category_id=category_ids.get("식당"), location=GeoJson(coordinates=[127.345, 36.364]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT, FoodIngredient.VEGETABLE], tastes=[], cooking_methods=[])),

        # --- 카페 (30개) ---
        ActivityModel(name="스타벅스 대전시청점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.385, 36.351]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.8, trend_level=0.7, vibe_level=0.2)),
        ActivityModel(name="투썸플레이스 둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.382, 36.354]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.8, trend_level=0.6, vibe_level=0.1)),
        ActivityModel(name="이디야커피 충남대점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.347, 36.362]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.9, trend_level=0.3, vibe_level=-0.2)),
        ActivityModel(name="카페그레이", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.380, 36.350]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=-0.7, trend_level=0.6, vibe_level=0.3)),
        ActivityModel(name="커피인터뷰", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.344, 36.365]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.8, trend_level=0.8, vibe_level=0.4)),
        ActivityModel(name="관저당", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.335, 36.305]), play_attributes=PlayAttributes(crowd_level=-0.2, activeness_level=-0.7, trend_level=0.4, vibe_level=-0.1)),
        ActivityModel(name="하치카페", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.420, 36.320]), play_attributes=PlayAttributes(crowd_level=0.0, activeness_level=-0.6, trend_level=0.5, vibe_level=0.2)),
        ActivityModel(name="비래키키", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.470, 36.375]), play_attributes=PlayAttributes(crowd_level=-0.4, activeness_level=-0.5, trend_level=0.6, vibe_level=0.1)),
        ActivityModel(name="우디룸", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.360, 36.357]), play_attributes=PlayAttributes(crowd_level=-0.3, activeness_level=-0.7, trend_level=0.5, vibe_level=0.0)),
        ActivityModel(name="성심당케익부띠끄", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.428, 36.327]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=-0.6, trend_level=0.9, vibe_level=0.5)),
        ActivityModel(name="빽다방 은행으능정이점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.429, 36.329]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.2, vibe_level=-0.3)),
        ActivityModel(name="공차 대전은행점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.427, 36.328]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.8, trend_level=0.4, vibe_level=0.0)),
        ActivityModel(name="설빙 대전둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.381, 36.352]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.7, trend_level=0.5, vibe_level=0.3)),
        ActivityModel(name="베스킨라빈스 대전시청점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.386, 36.350]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.8, trend_level=0.3, vibe_level=0.0)),
        ActivityModel(name="던킨도너츠 대전역점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.434, 36.332]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.1, vibe_level=-0.4)),
        ActivityModel(name="카페베네 유성온천점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.353, 36.355]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.8, trend_level=0.2, vibe_level=-0.1)),
        ActivityModel(name="할리스커피 대전둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.379, 36.353]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.8, trend_level=0.3, vibe_level=0.0)),
        ActivityModel(name="탐앤탐스 대전은행점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.428, 36.326]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.8, trend_level=0.2, vibe_level=-0.1)),
        ActivityModel(name="드롭탑 대전유성점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.349, 36.360]), play_attributes=PlayAttributes(crowd_level=0.2, activeness_level=-0.8, trend_level=0.1, vibe_level=-0.2)),
        ActivityModel(name="커피빈 대전갤러리아점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.382, 36.352]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.9, trend_level=0.5, vibe_level=0.1)),
        ActivityModel(name="폴바셋 대전신세계점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.385, 36.375]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.8, vibe_level=0.3)),
        ActivityModel(name="엔제리너스 대전관저점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.338, 36.308]), play_attributes=PlayAttributes(crowd_level=0.3, activeness_level=-0.9, trend_level=0.1, vibe_level=-0.3)),
        ActivityModel(name="파스쿠찌 대전복합터미널점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.432, 36.353]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.4, vibe_level=-0.1)),
        ActivityModel(name="크리스피크림도넛 둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.380, 36.352]), play_attributes=PlayAttributes(crowd_level=0.6, activeness_level=-0.8, trend_level=0.3, vibe_level=0.0)),
        ActivityModel(name="잠바주스 대전갤러리아점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.382, 36.352]), play_attributes=PlayAttributes(crowd_level=0.5, activeness_level=-0.8, trend_level=0.4, vibe_level=0.1)),
        ActivityModel(name="메가커피 충남대정문점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.350, 36.366]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=-0.9, trend_level=0.2, vibe_level=-0.4)),
        ActivityModel(name="컴포즈커피 대전시청역점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.384, 36.351]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.2, vibe_level=-0.3)),
        ActivityModel(name="매머드커피 대전둔산점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.378, 36.353]), play_attributes=PlayAttributes(crowd_level=0.7, activeness_level=-0.9, trend_level=0.2, vibe_level=-0.3)),
        ActivityModel(name="더리터 대전은행동점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.428, 36.328]), play_attributes=PlayAttributes(crowd_level=0.8, activeness_level=-0.9, trend_level=0.1, vibe_level=-0.5)),
        ActivityModel(name="감성커피 대전유성점", type=ActivityType.ACTIVITY, category_id=category_ids.get("카페"), location=GeoJson(coordinates=[127.352, 36.356]), play_attributes=PlayAttributes(crowd_level=0.4, activeness_level=-0.8, trend_level=0.3, vibe_level=-0.1)),
    ]
    
    activities.extend(additional_activities)

    # =================================================================================================
    # ========================================== 주점 데이터 (30개) ==========================================
    # =================================================================================================

    pub_activities = [
        # --- 주점 (30개) ---
        ActivityModel(name="역전할머니맥주 둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.381, 36.353]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="1987루프탑라운지 둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.383, 36.354]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL, FoodCookingMethod.LIQUID])),
        ActivityModel(name="인쌩맥주 충남대점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.348, 36.364]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="한신포차 대전은행점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.427, 36.327]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SPICY, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="크래프트피피", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.350, 36.361]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL, FoodCookingMethod.LIQUID])),
        ActivityModel(name="더초콜릿", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.379, 36.355]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SWEET, FoodTaste.BITTER], cooking_methods=[FoodCookingMethod.LIQUID])),
        ActivityModel(name="백스비어 대전시청점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.386, 36.350]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="구들마루", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.346, 36.363]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL, FoodCookingMethod.LIQUID])),
        ActivityModel(name="옥상", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.429, 36.325]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="김씨네심야식당", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.380, 36.352]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="용용선생 대전둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.382, 36.352]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.CHINESE], tastes=[FoodTaste.SPICY, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="금복주류", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.349, 36.365]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP, FoodCookingMethod.LIQUID])),
        ActivityModel(name="오늘와인한잔 대전둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.381, 36.354]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], tastes=[FoodTaste.SALTY, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.GRILL, FoodCookingMethod.LIQUID])),
        ActivityModel(name="말자싸롱 대전시청점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.384, 36.351]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="코다차야 대전둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.378, 36.353]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE, FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="느린하루", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.345, 36.361]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.SOUP, FoodCookingMethod.LIQUID])),
        ActivityModel(name="지금,보고싶다 대전은행점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.428, 36.328]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="단골손님 대전둔산점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.380, 36.354]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SPICY, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.SOUP, FoodCookingMethod.LIQUID])),
        ActivityModel(name="낭만집", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.347, 36.362]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.GRILL, FoodCookingMethod.LIQUID])),
        ActivityModel(name="예쁘다,밤", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.426, 36.326]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SWEET, FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="주인의주방", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.383, 36.351]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.RAW, FoodCookingMethod.LIQUID])),
        ActivityModel(name="뉴욕야시장 대전궁동점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.348, 36.362]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.WESTERN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="미스터오징어", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.385, 36.355]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.FISH], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.RAW, FoodCookingMethod.LIQUID])),
        ActivityModel(name="오사카부루스", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.429, 36.329]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.JAPANESE], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="포차어게인", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.381, 36.352]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STIR_FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="달빛맥주", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.349, 36.361]), food_attributes=FoodAttributes(cuisine_types=[], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="가장맛있는족발", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.377, 36.352]), food_attributes=FoodAttributes(cuisine_types=[FoodCuisineType.KOREAN], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.STEAMED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="또봉이통닭", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.415, 36.340]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="BHC치킨 대전은행점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.428, 36.326]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY, FoodTaste.SPICY], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
        ActivityModel(name="교촌치킨 유성점", type=ActivityType.FOOD, category_id=category_ids.get("주점"), location=GeoJson(coordinates=[127.351, 36.358]), food_attributes=FoodAttributes(cuisine_types=[], ingredients=[FoodIngredient.MEAT], tastes=[FoodTaste.SALTY, FoodTaste.SWEET], cooking_methods=[FoodCookingMethod.FRIED, FoodCookingMethod.LIQUID])),
    ]

    activities.extend(pub_activities)
    return activities
